### ISSUE TITLE
Dont Block Ads

### ISSUE THREAD

**Issue by HakanDOGAN1981** [AdguardTeam/ContentBlocker#206] opened 2019-11-21 12:16 UTC
On my Phone dont Block any ads. With Yandex Browser. 
Asus Zenfone 5Z 

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| v2.55
| Browser in use:| Yandex Browser
| Filters enabled in Adguard:| Turkish English, Annoyances
| Device model:Asus Zenfone 5Z 
| Operating system and version:| Android 9.0
| Rooted or not? | No

**Comment by artemiv4nov** [comment] 2019-11-21 12:26
This task is a duplicate of #203 
The current version of the Yandex browser has a bug: they don't use ad blockers for HTTP sites.

**Closed by artemiv4nov** 2019-11-21 12:26 UTC
