### ISSUE TITLE
Problems on apkmirror site?

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/ContentBlocker#107] opened 2018-03-03 16:34 UTC
Hi!
Maybe are there problem on apkmirror.com?
I see a lot of blank spaces.

### Steps to reproduce:
1. open Samsung Internet browser
2. go to apkmirror.com

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| 2.1.2 |
| Browser in use:| Samsung Internet 6.4.10.5 |
| Filters enabled in Adguard:| default list - UsefulAdsFilter + AnnoyancesFilter |
| Operating system and version:| LineageOS 14.1 |
| Rooted or not? | No |

**Comment by ameshkov** [comment] 2018-03-03 19:51
@Alex-302 could you please take a look?

**Comment by ameshkov** [comment] 2018-03-04 20:45
Issue moved to [AdguardTeam/AdguardFilters #12611](https://github.com/AdguardTeam/AdguardFilters/issues/12611) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment] 2018-03-05 10:35
they are must be hidden by
```
apkmirror.com##.gooWidget
##.google-ad-square-sidebar
```
I don't know why they are not applied.

**Comment by ameshkov** [comment] 2018-03-05 10:42
Happens in Samsung browser only?

**Comment by Alex-302** [comment] 2018-03-05 13:21
And Yandex.

**Comment by ameshkov** [comment] 2018-03-05 13:26
Do you them both in the optimized version of filters?

**Comment by Alex-302** [comment] 2018-03-05 18:11
I tried to add required rules to user filter with enabled/disabled filters/

**Comment by superlex** [comment] 2018-03-05 18:32
In my case Yandex Browser 18.1 (build 0.527) works well, the bug affects only Samsung Internet.

**Comment by ameshkov** [comment] 2018-03-10 00:28
It works with a clean user filter. However, the issue is easily reproducible when I enable the default set of filters.

It might be a bug of Samsung Internet and we'd better figure out what it is exactly.

**Comment by superlex** [comment] 2018-03-10 12:04
If it can help you, I tried with an other adblocker (Adblock Plus for Samsung Internet) and it works well on apkmirror.

**Comment by superlex** [comment] 2018-03-10 18:40
@ameshkov 
> It works with a clean user filter. However, the issue is easily reproducible when I enable the default set of filters.
Ok, it's because of English list.
I found that removing these 2 lines
apkmirror.com##body .google-ad-leaderboard-smaller:style(position: absolute!important; left: -4000px!important; display:block!important;)
apkmirror.com##body .google-ad-square-sidebar:style(position: absolute!important; left: -4000px!important; display:block!important;)
it works well. Are they needed?
I found these 5 lines could be sufficient:
##.google-ad-square-sidebar
##.advertisement-text
apkmirror.com##.gooWidget
apkmirror.com##.google-ad-leaderboard
apkmirror.com##.google-ad-leaderboard-injected
Do you confirm?

**Comment by ameshkov** [comment] 2018-03-11 10:27
@superlex awesome, thank you for the investigation!

The problem is on the server side, these rules should've been transformed automatically to the `#$#` rules syntax: https://github.com/AdguardTeam/FiltersCompiler/issues/14

Closing this as duplicate

**Comment by superlex** [comment] 2018-03-11 12:37
You're welcome, thanks to you :)

**Comment by superlex** [comment] 2018-04-14 00:38
Hi @ameshkov ,
the rules have been transformed to the #$#, however the issue is not fixed.
Adding

```
apkmirror.com#@#body .google-ad-leaderboard-smaller:style(position: absolute!important; left: -4000px!important; display:block!important;)
apkmirror.com#@#body .google-ad-square-sidebar:style(position: absolute!important; left: -4000px!important; display:block!important;)
```

to user filter list fixes the issue, so there is still some problem with them.

**Comment by ameshkov** [comment] 2018-04-14 00:40
I've reopened https://github.com/AdguardTeam/FiltersCompiler/issues/14 we'll see what's wrong

**Comment by superlex** [comment] 2018-04-14 00:41
Ok, thanks.

**Comment by superlex** [comment] 2018-04-14 01:14
Note that if you disable English list and you add 
```
##.google-ad-square-sidebar
##.advertisement-text
apkmirror.com##.gooWidget
apkmirror.com##.google-ad-leaderboard
apkmirror.com##.google-ad-leaderboard-injected
apkmirror.com#$#body .google-ad-leaderboard-smaller { position: absolute!important; left: -4000px!important; display:block!important; }
apkmirror.com#$#body .google-ad-square-sidebar { position: absolute!important; left: -4000px!important; display:block!important; }
```
to user list they work well. 
Then, another question:
https://filters.adtidy.org/extension/android-content-blocker/filters/2.txt
here these rules are not present.

**Comment by ameshkov** [comment] 2018-04-14 14:12
So weird, especially the `:style` exceptions part.

@admitrevskiy try reproducing the issue on your side and check what's wrong.

**Comment by superlex** [comment] 2018-04-17 18:28
> So weird, especially the :style exceptions part.

I don't know.
Also, I don't understand why the rule
`apkmirror.com#@#.gooWidget`
causes this issue in Samsung Internet but not in Yandex browser.

**Comment by superlex** [comment] 2018-04-17 22:55
Ok, I've some news.

> So weird, especially the :style exceptions part.

It's not because of **:style**, it's because of **:**
What does **:** mean?
I think it means "don't consider this rule" or "remove this rule", because adding
`apkmirror.com#@#body .google-ad-square-sidebar:`
to user filter list fixes the issue. Alternately, you can add to user filter list
`apkmirror.com#@#.gooWidget:`
that removes 
`apkmirror.com#@#.gooWidget`
rule.

Now, I don't know why 
`apkmirror.com#@#.gooWidget`
causes the issue in Samsung Internet but not in Yandex Browser, maybe it's because of Samsung browser limitations as #106 . Infact there the problem is the rule
`~sinemia.com,~9to5google.com,~9to5mac.com,~9to5toys.com,~electrek.co##.header-social`
and adding
`~sinemia.com,~9to5google.com,~9to5mac.com,~9to5toys.com,~electrek.co##.header-social:`
to user filter fixes the issue.

**Comment by ameshkov** [comment] 2018-04-18 07:54
@superlex thank you! I am still not sure what's going on as `body .google-ad-square-sidebar:` is not a valid selector (`:` with no pseudo-class following it is invalid).

@admitrevskiy you need to use `chrome://inspect` to figure what's hidden (or not hidden) on the page.

**Comment by superlex** [comment] 2018-04-19 14:41
You're welcome :)
Ok, so `:` is invalid. Infact rules ending with it are ignored by Yandex, maybe Samsung Internet not being able to interpret it removes that rule.

Is there an official way to tell ContentBlocker that a rule is more important than another one (e.g. in order to override an exception rule)?

**Comment by Alex-302** [comment] 2018-04-19 21:16
It is not a bug. I forgot about two element hiding exclusions:( They are removed now.

**Comment by superlex** [comment] 2018-04-19 21:35
@Alex-302 
But it was present only in Samsung Internet, if I'm not wrong.
Something similar happens in #106 too, there you could try to remove
` ~sinemia.com,~9to5google.com,~9to5mac.com,~9to5toys.com,~electrek.co##.header-social`

**Comment by superlex** [comment] 2019-03-23 17:50
@ameshkov @Alex-302 
Hi,
this issue is back.
It seems to be caused by #@#.gooWidget

**Comment by Alex-302** [comment] 2019-03-25 16:16
Please check
`apkmirror.com##body .gooWidget`

**Comment by superlex** [comment] 2019-03-25 16:41
> Please check
> apkmirror.com##body .gooWidget

Thanks @Alex-302 ,
it works very well with Yandex and Safari, but it doesn't work with Samung Internet, unfortunately.

**Comment by Alex-302** [comment] 2019-03-25 17:12
try this
`apkmirror.com##div .gooWidget`
it is the same as the rule above, just a different CSS selector.

**Comment by superlex** [comment] 2019-03-25 17:40
Same as before: it works with Yandex and Safari, but it doesn't work with Samsung Internet.

**Comment by Alex-302** [comment] 2019-03-25 18:00
Ok. When you try to download do you see timers or something like that(antiadblock messages etc.)?

**Comment by superlex** [comment] 2019-03-25 18:35
If it can help you, I also tried
```
apkmirror.com##div.gooWidget
apkmirror.com##[class^="gooWidget"]
```
: they work with Yandex and Safari but not with Samsung Internet, as the previous rules.

> Ok. When you trying to download do you see timers or something like that(antiadblock messages etc.)?

No I don't :)

**Closed** 2019-03-25 19:14 UTC
Labels: bug

**Comment by Alex-302** [comment] 2019-03-25 19:24
Please check for updates after one hour.



> I see ads with Yandex but not with Samsung Internet

maybe browser's bug.

**Comment by superlex** [comment] 2019-03-25 23:07
@Alex-302 
Sorry, now 
- with Firefox + AdGuard I see the cat with timer;
- with Samsung Internet and Yandex I see blank spaces.
I'll check again tomorrow.
Thanks.

**Comment by Alex-302** [comment] 2019-03-26 10:24
Changed the rules. Please check again.

**Comment by superlex** [comment] 2019-03-26 12:51
Now it's ok as regards Firefox + AG Ext, I see white spaces in Yandex, Safari and Internet Samsung but 
`apkmirror.com##div .gooWidget`
works well with all 3 browsers.
Thanks :)

So, if I'm understanding the problem, 
- #@#.gooWidget is not needed (infact you removed it but I see white space again, needed because of antiadblock, so that's right);
- if there is #@#.gooWidget the rule that you suggest me
`apkmirror.com##div .gooWidget`
works with Yandex and Safari but it doesn't work with Samsung Internet.
Is this a bug of CB or of Samsung Internet?

**Comment by Alex-302** [comment] 2019-03-26 13:13
> Is this a bug of CB or of Samsung Internet?

I think this is a bug of browser. CB works in another way unlike AG for Android.

**Comment by superlex** [comment] 2019-03-26 13:38
> I think this is a bug of browser. CB works in another way unlike AG for Android.

I understand.
I'm able to reproduce the issue with other sites too

> site##.class
> site#@#.class
> site##div.class

.class is hided in Yandex but not in Samsung Internet.

Please, could you take a look of #106 too?
Maybe you could change the rule
`~gardenista.com,~sinemia.com,~9to5google.com,~9to5mac.com,~9to5toys.com,~electrek.co##.header-social`
in order to be compatible with Samsung Internet too.

Thank you very much.

**Comment by superlex** [comment] 2019-07-09 21:41
@Alex-302 
It looks like
`apkmirror.com#@#.gooWidget`
it's needed for AG for Safari.
See https://github.com/AdguardTeam/AdGuardForSafari/issues/144#issuecomment-486752836 and https://github.com/AdguardTeam/AdGuardForSafari/issues/144#issuecomment-493679704
Thanks.

**Comment by Alex-302** [comment] 2019-07-10 10:06
ok, enabled that rule
